Update draive

diff --git a/chat/Makefile b/chat/Makefile
--- a/chat/Makefile
+++ b/chat/Makefile
@@ -8,74 +8,79 @@ SOURCES_PATH := src
 # load environment config from .env if able
 -include .env
 
-ifndef PYTHON_ALIAS
-	PYTHON_ALIAS := python
+ifndef UV_VERSION
+	UV_VERSION := 0.5.15
 endif
 
-ifndef UV_ALIAS
-	UV_ALIAS := uv
-endif
+.PHONY: uv_check venv sync update format lint chat_run docker_run
 
-ifndef INSTALL_OPTIONS
-	INSTALL_OPTIONS := .[dev]
-endif
+# Check installed UV version and install if needed
+uv_check:
+	@echo 'Checking uv version...'
 
-ifndef CHAINLIT_PORT
-	CHAINLIT_PORT := 8888
-endif
+	# Install if not present
+	@if ! command -v uv > /dev/null; then \
+		echo '...installing uv...'; \
+		curl -LsSf https://github.com/astral-sh/uv/releases/download/$(UV_VERSION)/uv-installer.sh | sh; \
+		if [ $$? -ne 0 ]; then \
+			echo "...installing uv failed!"; \
+			exit 1; \
+		fi; \
+	fi
 
-.PHONY: install venv sync lock update format lint run docker_run
-
-# Install in system without virtual environment and extras. DO NOT USE FOR DEVELOPMENT
-install:
-	@echo '# Installing...'
-	@echo '...preparing dependencies...'
-	@pip install $(INSTALL_OPTIONS) --system --constraint constraints
-	@echo '...finished!'
+	# Check version and update if needed
+	@if command -v uv > /dev/null; then \
+		CURRENT_VERSION=$$(uv --version | head -n1 | cut -d" " -f2); \
+		if [ "$$(printf "%s\n%s" "$(UV_VERSION)" "$$CURRENT_VERSION" | sort -V | head -n1)" != "$(UV_VERSION)" ]; then \
+			echo '...updating uv...'; \
+			curl -LsSf https://github.com/astral-sh/uv/releases/download/$(UV_VERSION)/uv-installer.sh | sh; \
+			if [ $$? -ne 0 ]; then \
+				echo "...updating uv failed!"; \
+				exit 1; \
+			fi; \
+		else \
+			echo '...uv version is up-to-date!'; \
+		fi; \
+	fi
 
 # Setup virtual environment for local development.
-venv:
+venv: uv_check
 	@echo '# Preparing development environment...'
 	@echo '...cloning .env...'
 	@cp -n ./config/.env.example ./.env || :
+	@echo '...preparing git hooks...'
+	@cp -n ./config/pre-push ./.git/hooks/pre-push || :
 	@echo '...preparing venv...'
-	@$(PYTHON_ALIAS) -m venv .venv --prompt="VENV[DEV]" --clear --upgrade-deps
-	@. ./.venv/bin/activate && pip install --upgrade pip && pip install --editable $(INSTALL_OPTIONS) --constraint constraints
+	@uv sync --all-groups --all-extras --frozen --reinstall
 	@echo '...development environment ready! Activate venv using `. ./.venv/bin/activate`.'
 
 # Sync environment with uv based on constraints
-sync:
+sync: uv_check
 	@echo '# Synchronizing dependencies...'
-	@$(UV_ALIAS) pip install --editable $(INSTALL_OPTIONS) --constraint constraints
-	@echo '...finished!'
-
-# Generate a set of locked dependencies from pyproject.toml
-lock:
-	@echo '# Locking dependencies...'
-	@$(UV_ALIAS) pip compile pyproject.toml -o constraints --all-extras
+	@uv sync --all-groups --all-extras --frozen
 	@echo '...finished!'
 
 # Update and lock dependencies from pyproject.toml
 update:
 	@echo '# Updating dependencies...'
-	@$(UV_ALIAS) --no-cache pip compile pyproject.toml -o constraints --all-extras --upgrade
-	@$(UV_ALIAS) pip install --editable $(INSTALL_OPTIONS) --constraint constraints
+	@uv sync --all-groups --all-extras --upgrade
 	@echo '...finished!'
 
 # Run formatter.
 format:
-	@ruff --quiet --fix $(SOURCES_PATH) $(TESTS_PATH)
+	@ruff check --quiet --fix $(SOURCES_PATH)
+	@ruff format --quiet $(SOURCES_PATH)
 
 # Run linters and code checks.
 lint:
 	@bandit -r $(SOURCES_PATH)
-	@ruff check $(SOURCES_PATH) $(TESTS_PATH)
+	@ruff check $(SOURCES_PATH)
 	@pyright --project ./
 
-# Run local server with hot reload.
-run:
-	chainlit run ./src/entrypoint/chat.py -w
+# Run local development api server
+chat_run:
+	@chainlit run ./src/entrypoint/chat.py -w
 
-# Run all services locally using docker-compose.
+# Run services locally using docker-compose.
 docker_run:
-	@docker-compose up --force-recreate --build chat
+	@docker compose up --force-recreate --build chat
